onMessage(APP_MESSAGE_PROCESS_KEY_DOWN, "processKeyDown")
onMessage(APP_MESSAGE_PROCESS_KEY_UP, "processKeyUp")
onMessage(APP_MESSAGE_RESET_STATES, "resetStates")
onMessage(APP_MESSAGE_FORCE_QUIT, "exitHookHandler")
onMessage(APP_MESSAGE_TOGGLE_STICKY_KEYS_MONITORING, "toggleStickyKeysMonitoring")
