onMessage(APP_MESSAGE_PROCESS_KEY_DOWN, "processKeyDown")
onMessage(APP_MESSAGE_PROCESS_KEY_UP, "processKeyUp")
onMessage(APP_MESSAGE_FORCE_QUIT, "exitHookHandler")
onMessage(APP_MESSAGE_FORCE_RELOAD, "reloadHookHandler")
onMessage(APP_MESSAGE_RESET_HOOK_MONITORING, "restartHookHandlerMonitoring")
onMessage(APP_MESSAGE_STORE_DEBUG_LOG, "storeDebugLogHookHandler")
